{
  "formatVersion": "1.1",
  "component": {
    "group": "com.lawnchair",
    "module": "unfold",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.1"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "unfold-1.0.0.aar",
          "url": "unfold-1.0.0.aar",
          "size": 162119,
          "sha512": "a93831e02b9f53b9dcad442a46b49148a591df4d0dd8872e4c780047f3a538a35ae0b1f5ba05f5d7166e3bbbf973611017d0370a113735a69587191e38e8d2a2",
          "sha256": "7d339ca290eb88b91e398036555732e403e96544a9f86311ab5386d3faa88d65",
          "sha1": "051780ad936e9372140ca2e6ff9fc0341a223864",
          "md5": "16ce82c190b09f544ea776243ec19c5e"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.17.0"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "hilt-android",
          "version": {
            "requires": "2.57.2"
          }
        },
        {
          "group": "androidx.concurrent",
          "module": "concurrent-futures",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-common",
          "version": {
            "requires": "2.10.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "unfold-1.0.0.aar",
          "url": "unfold-1.0.0.aar",
          "size": 162119,
          "sha512": "a93831e02b9f53b9dcad442a46b49148a591df4d0dd8872e4c780047f3a538a35ae0b1f5ba05f5d7166e3bbbf973611017d0370a113735a69587191e38e8d2a2",
          "sha256": "7d339ca290eb88b91e398036555732e403e96544a9f86311ab5386d3faa88d65",
          "sha1": "051780ad936e9372140ca2e6ff9fc0341a223864",
          "md5": "16ce82c190b09f544ea776243ec19c5e"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "unfold-1.0.0-sources.jar",
          "url": "unfold-1.0.0-sources.jar",
          "size": 84057,
          "sha512": "63f9b717a8165d808f3ffa985c6d20076f5d6b2b28ce0c851e18886f2dd70d7e7598f34c4bc87f982baf5026849c4a87f33333ddc0ae021126e403732d421c06",
          "sha256": "bc789a6af8a8405023f804ab6d9db484f2bea011786010560b9cbb0fc5eb736c",
          "sha1": "b6b05db7a18141d7553ff98afb5e7e12fb24e8a6",
          "md5": "bfbad9466ebbf02e211e8e7562323024"
        }
      ]
    }
  ]
}
