{
  "formatVersion": "1.1",
  "component": {
    "group": "com.lawnchair",
    "module": "launcher-sdk-debug",
    "version": "1.0.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.1"
    }
  },
  "variants": [
    {
      "name": "lawnWithQuickstepPlayDebugApiElements-published",
      "attributes": {
        "app": "lawn",
        "channel": "play",
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "com.android.build.api.attributes.ProductFlavor:app": "lawn",
        "com.android.build.api.attributes.ProductFlavor:channel": "play",
        "com.android.build.api.attributes.ProductFlavor:recents": "withQuickstep",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm",
        "recents": "withQuickstep"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "launcher-sdk-debug-1.0.3.aar",
          "url": "launcher-sdk-debug-1.0.3.aar",
          "size": 16197573,
          "sha512": "1ce00d85042eb2c9f38889b5e4a5567252faecaabb81438a6fa3a79cf68ff43f6ad06e23ca5473ea12a470638add7a5c5757cc014b6f37cf7a600dd863361b1b",
          "sha256": "3b1a5e8c8c5b10a9962d7253d745454a0ba509c93909bf8baf683d940156c5e7",
          "sha1": "6116a064ac0830f6b8c425d23c5d382cd23ca1d3",
          "md5": "c7fb9d50ff1365d5bde2092a772f4b10"
        }
      ]
    },
    {
      "name": "lawnWithQuickstepPlayDebugRuntimeElements-published",
      "attributes": {
        "app": "lawn",
        "channel": "play",
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "com.android.build.api.attributes.ProductFlavor:app": "lawn",
        "com.android.build.api.attributes.ProductFlavor:channel": "play",
        "com.android.build.api.attributes.ProductFlavor:recents": "withQuickstep",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm",
        "recents": "withQuickstep"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-parcelize-runtime",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling"
        },
        {
          "group": "com.lawnchair",
          "module": "shared",
          "version": {
            "requires": "1.0.3"
          }
        },
        {
          "group": "com.lawnchair",
          "module": "anim",
          "version": {
            "requires": "1.0.3"
          }
        },
        {
          "group": "com.lawnchair",
          "module": "unfold",
          "version": {
            "requires": "1.0.3"
          }
        },
        {
          "group": "com.lawnchair",
          "module": "viewcapture",
          "version": {
            "requires": "1.0.3"
          }
        },
        {
          "group": "com.lawnchair",
          "module": "log",
          "version": {
            "requires": "1.0.3"
          }
        },
        {
          "group": "com.lawnchair",
          "module": "plugincore",
          "version": {
            "requires": "1.0.3"
          }
        },
        {
          "group": "com.lawnchair",
          "module": "compatLib",
          "version": {
            "requires": "1.0.3"
          }
        },
        {
          "group": "com.lawnchair",
          "module": "compatLibVQ",
          "version": {
            "requires": "1.0.3"
          }
        },
        {
          "group": "com.lawnchair",
          "module": "compatLibVR",
          "version": {
            "requires": "1.0.3"
          }
        },
        {
          "group": "com.lawnchair",
          "module": "compatLibVS",
          "version": {
            "requires": "1.0.3"
          }
        },
        {
          "group": "com.lawnchair",
          "module": "compatLibVT",
          "version": {
            "requires": "1.0.3"
          }
        },
        {
          "group": "com.lawnchair",
          "module": "compatLibVU",
          "version": {
            "requires": "1.0.3"
          }
        },
        {
          "group": "com.lawnchair",
          "module": "compatLibVV",
          "version": {
            "requires": "1.0.3"
          }
        },
        {
          "group": "com.lawnchair",
          "module": "wmshell",
          "version": {
            "requires": "1.0.3"
          }
        },
        {
          "group": "com.lawnchair",
          "module": "flags",
          "version": {
            "requires": "1.0.3"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.17.0"
          }
        },
        {
          "group": "com.google.protobuf",
          "module": "protobuf-javalite",
          "version": {
            "requires": "4.33.2"
          }
        },
        {
          "group": "com.lawnchair",
          "module": "iconloaderlib",
          "version": {
            "requires": "1.0.3"
          }
        },
        {
          "group": "com.lawnchair",
          "module": "searchuilib",
          "version": {
            "requires": "1.0.3"
          }
        },
        {
          "group": "com.lawnchair",
          "module": "animationlib",
          "version": {
            "requires": "1.0.3"
          }
        },
        {
          "group": "androidx.dynamicanimation",
          "module": "dynamicanimation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.profileinstaller",
          "module": "profileinstaller",
          "version": {
            "requires": "1.4.1"
          }
        },
        {
          "group": "androidx.recyclerview",
          "module": "recyclerview",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "androidx.preference",
          "module": "preference-ktx",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "com.github.ChickenHook",
          "module": "RestrictionBypass",
          "version": {
            "requires": "2.2"
          }
        },
        {
          "group": "dev.rikka.tools.refine",
          "module": "runtime",
          "version": {
            "requires": "4.4.0"
          }
        },
        {
          "group": "androidx.compose",
          "module": "compose-bom",
          "version": {
            "requires": "2025.12.01"
          },
          "attributes": {
            "org.gradle.category": "platform"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-util"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling-preview"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-text-google-fonts"
        },
        {
          "group": "androidx.compose.foundation",
          "module": "foundation"
        },
        {
          "group": "androidx.compose.material",
          "module": "material-icons-extended",
          "version": {
            "requires": "1.7.8"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-livedata"
        },
        {
          "group": "androidx.compose.material3",
          "module": "material3"
        },
        {
          "group": "androidx.compose.material3",
          "module": "material3-window-size-class"
        },
        {
          "group": "androidx.activity",
          "module": "activity-compose",
          "version": {
            "requires": "1.12.2"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-compose",
          "version": {
            "requires": "2.10.0"
          }
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-compose",
          "version": {
            "requires": "2.9.6"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout",
          "version": {
            "requires": "2.2.1"
          }
        },
        {
          "group": "androidx.palette",
          "module": "palette-ktx",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.slice",
          "module": "slice-core",
          "version": {
            "requires": "1.1.0-alpha02"
          }
        },
        {
          "group": "com.google.accompanist",
          "module": "accompanist-adaptive",
          "version": {
            "requires": "0.37.3"
          }
        },
        {
          "group": "com.google.accompanist",
          "module": "accompanist-drawablepainter",
          "version": {
            "requires": "0.37.3"
          }
        },
        {
          "group": "com.google.accompanist",
          "module": "accompanist-permissions",
          "version": {
            "requires": "0.37.3"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.13.0"
          }
        },
        {
          "group": "io.github.fornewid",
          "module": "material-motion-compose-core",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "dev.kdrag0n",
          "module": "colorkt",
          "version": {
            "requires": "1.0.5"
          }
        },
        {
          "group": "io.coil-kt",
          "module": "coil-compose",
          "version": {
            "requires": "2.7.0"
          }
        },
        {
          "group": "me.xdrop",
          "module": "fuzzywuzzy",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "com.patrykmichalik.opto",
          "module": "domain",
          "version": {
            "requires": "1.0.18"
          }
        },
        {
          "group": "com.patrykmichalik.opto",
          "module": "core",
          "version": {
            "requires": "1.0.18"
          }
        },
        {
          "group": "com.patrykmichalik.opto",
          "module": "compose",
          "version": {
            "requires": "1.0.18"
          }
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-preferences",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-kotlinx-serialization",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "5.3.2"
          }
        },
        {
          "group": "androidx.room",
          "module": "room-runtime",
          "version": {
            "requires": "2.8.4"
          }
        },
        {
          "group": "androidx.room",
          "module": "room-ktx",
          "version": {
            "requires": "2.8.4"
          }
        },
        {
          "group": "com.github.topjohnwu.libsu",
          "module": "service",
          "version": {
            "requires": "6.0.0"
          }
        },
        {
          "group": "com.github.samanzamani",
          "module": "PersianDate",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "com.airbnb.android",
          "module": "lottie",
          "version": {
            "requires": "6.7.1"
          }
        },
        {
          "group": "sh.calvin.reorderable",
          "module": "reorderable",
          "version": {
            "requires": "2.5.1"
          }
        },
        {
          "group": "com.kieronquinn.smartspacer",
          "module": "sdk-client",
          "version": {
            "requires": "1.1.2"
          },
          "excludes": [
            {
              "group": "com.github.skydoves",
              "module": "balloon"
            }
          ]
        },
        {
          "group": "io.github.hokofly",
          "module": "hoko-blur",
          "version": {
            "requires": "1.5.5"
          }
        },
        {
          "group": "androidx.window",
          "module": "window",
          "version": {
            "requires": "1.5.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "launcher-sdk-debug-1.0.3.aar",
          "url": "launcher-sdk-debug-1.0.3.aar",
          "size": 16197573,
          "sha512": "1ce00d85042eb2c9f38889b5e4a5567252faecaabb81438a6fa3a79cf68ff43f6ad06e23ca5473ea12a470638add7a5c5757cc014b6f37cf7a600dd863361b1b",
          "sha256": "3b1a5e8c8c5b10a9962d7253d745454a0ba509c93909bf8baf683d940156c5e7",
          "sha1": "6116a064ac0830f6b8c425d23c5d382cd23ca1d3",
          "md5": "c7fb9d50ff1365d5bde2092a772f4b10"
        }
      ]
    },
    {
      "name": "lawnWithQuickstepPlayDebugSourcesElements-published",
      "attributes": {
        "app": "lawn",
        "channel": "play",
        "com.android.build.api.attributes.BuildTypeAttr": "debug",
        "com.android.build.api.attributes.ProductFlavor:app": "lawn",
        "com.android.build.api.attributes.ProductFlavor:channel": "play",
        "com.android.build.api.attributes.ProductFlavor:recents": "withQuickstep",
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm",
        "recents": "withQuickstep"
      },
      "files": [
        {
          "name": "launcher-sdk-debug-1.0.3-sources.jar",
          "url": "launcher-sdk-debug-1.0.3-sources.jar",
          "size": 9926853,
          "sha512": "fbfd514df8163073c3c93270af921dc59c75f51e8a09349def3d6d21d2e0c6d8e6e6c7530730b4cadf20e8c9b9e557f902b567c80d2cc078fce08920a53a034d",
          "sha256": "a86b098339a0bcb5cafb2c12935d6ab69ad208a9898e2956c41023a13a263f2f",
          "sha1": "c3b7163dfd81c8fb88c8d714b9353dd07ef8c38a",
          "md5": "9bac3fb0379789328e63caa07fc5800d"
        }
      ]
    }
  ]
}
