{
  "formatVersion": "1.1",
  "component": {
    "group": "com.lawnchair",
    "module": "plugincore",
    "version": "1.0.14",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.1"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "plugincore-1.0.14.aar",
          "url": "plugincore-1.0.14.aar",
          "size": 6500,
          "sha512": "ee13b70b104ae876941911b7cf73b40b0dcce3b157691195f97858e8179d09709ff6739d33736a37dbd6b5363e2dcbc0a4e957df5c2503f98f8080a8ab842788",
          "sha256": "2a04d90ba242e39ae5ca48d507b4e586b2c838fe57c68a41df5c5d75947a0ed5",
          "sha1": "2ce81e3c842c79f597d35fa4694af9b0ca112a9f",
          "md5": "691226a773ae592aa556b7d3786a3385"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.17.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "plugincore-1.0.14.aar",
          "url": "plugincore-1.0.14.aar",
          "size": 6500,
          "sha512": "ee13b70b104ae876941911b7cf73b40b0dcce3b157691195f97858e8179d09709ff6739d33736a37dbd6b5363e2dcbc0a4e957df5c2503f98f8080a8ab842788",
          "sha256": "2a04d90ba242e39ae5ca48d507b4e586b2c838fe57c68a41df5c5d75947a0ed5",
          "sha1": "2ce81e3c842c79f597d35fa4694af9b0ca112a9f",
          "md5": "691226a773ae592aa556b7d3786a3385"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "plugincore-1.0.14-sources.jar",
          "url": "plugincore-1.0.14-sources.jar",
          "size": 11947,
          "sha512": "c41b4c8719afee87a7f0e2e0aaa59ab223d25c52e4443a51c9114acb7bd6fd49166e1720663582493deb1535879b165f8ebcb16ce003a0c3b75ad6efc2d35c2b",
          "sha256": "673a5904a1ea4143632bfad635cd7c99f960798a6024fafb800b3f6d28f3316f",
          "sha1": "d85d58de8590cfa8597f4899144b18d2e2bbe5d8",
          "md5": "3ddb7fe3358c1062df562316e7eae86d"
        }
      ]
    }
  ]
}
