{
  "formatVersion": "1.1",
  "component": {
    "group": "com.lawnchair",
    "module": "plugin",
    "version": "1.0.14",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.1"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "plugin-1.0.14.aar",
          "url": "plugin-1.0.14.aar",
          "size": 73443,
          "sha512": "bcc5955d529e45f6370015d6003d2bb781a7b2f051fcb2797965dc51f90e339b73c3a926ce94bbbaa1a1fbe7ef0f5ce8f2a10a043b81973a789e9c0838b27e1a",
          "sha256": "28d0548715deb838da11c9c526213b95076792da4e8af964561bed2d0fa19f35",
          "sha1": "7f6cdb4c6b5f37a9d2c67924d1197fc92429dc42",
          "md5": "31638f5f97409f321992e4ebef06863a"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.17.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "plugin-1.0.14.aar",
          "url": "plugin-1.0.14.aar",
          "size": 73443,
          "sha512": "bcc5955d529e45f6370015d6003d2bb781a7b2f051fcb2797965dc51f90e339b73c3a926ce94bbbaa1a1fbe7ef0f5ce8f2a10a043b81973a789e9c0838b27e1a",
          "sha256": "28d0548715deb838da11c9c526213b95076792da4e8af964561bed2d0fa19f35",
          "sha1": "7f6cdb4c6b5f37a9d2c67924d1197fc92429dc42",
          "md5": "31638f5f97409f321992e4ebef06863a"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "plugin-1.0.14-sources.jar",
          "url": "plugin-1.0.14-sources.jar",
          "size": 46945,
          "sha512": "e55463a6c77718bacd5b0562ee453f906af5d04fa919304aa8aea59e65c97858dc425f8b872ff0d6411f3406fcde005afe157d48c7c232b7270b303c986c1152",
          "sha256": "063cb7896b93d73d8bf8b43f78b13827fd29447ff789bf4e3b1c25253d400962",
          "sha1": "4b3183f64c8db3fce94d19c757140e984e544fe1",
          "md5": "ae81ef65f18d56c869463991ba153306"
        }
      ]
    }
  ]
}
