{
  "formatVersion": "1.1",
  "component": {
    "group": "com.lawnchair",
    "module": "launcher-sdk",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.1"
    }
  },
  "variants": [
    {
      "name": "lawnWithQuickstepPlayReleaseApiElements-published",
      "attributes": {
        "app": "lawn",
        "channel": "play",
        "com.android.build.api.attributes.ProductFlavor:app": "lawn",
        "com.android.build.api.attributes.ProductFlavor:channel": "play",
        "com.android.build.api.attributes.ProductFlavor:recents": "withQuickstep",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm",
        "recents": "withQuickstep"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "launcher-sdk-1.0.0.aar",
          "url": "launcher-sdk-1.0.0.aar",
          "size": 15617526,
          "sha512": "9ffc5b96eb02b7f77477d78e276a72c04e3b92e56849b1013d325a82ef381556518f8c55774b7a38ef03e07a5fbd535e9b179054a0957567cacc2c29ab626c20",
          "sha256": "3f93ecfb79ae82282465d2e80230b6fb18c17f8d4ec6d11b2992b48fc9027048",
          "sha1": "c434cad5044da45fce19d404cdecd14c8451db75",
          "md5": "2520ef227cd0766267bcedfd2712f898"
        }
      ]
    },
    {
      "name": "lawnWithQuickstepPlayReleaseRuntimeElements-published",
      "attributes": {
        "app": "lawn",
        "channel": "play",
        "com.android.build.api.attributes.ProductFlavor:app": "lawn",
        "com.android.build.api.attributes.ProductFlavor:channel": "play",
        "com.android.build.api.attributes.ProductFlavor:recents": "withQuickstep",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm",
        "recents": "withQuickstep"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-parcelize-runtime",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "com.lawnchair",
          "module": "shared",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "com.lawnchair",
          "module": "anim",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "com.lawnchair",
          "module": "unfold",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "com.lawnchair",
          "module": "viewcapture",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "com.lawnchair",
          "module": "log",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "com.lawnchair",
          "module": "plugincore",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "com.lawnchair",
          "module": "compatLib",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "com.lawnchair",
          "module": "compatLibVQ",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "com.lawnchair",
          "module": "compatLibVR",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "com.lawnchair",
          "module": "compatLibVS",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "com.lawnchair",
          "module": "compatLibVT",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "com.lawnchair",
          "module": "compatLibVU",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "com.lawnchair",
          "module": "compatLibVV",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "com.lawnchair",
          "module": "wmshell",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "com.lawnchair",
          "module": "flags",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.17.0"
          }
        },
        {
          "group": "com.google.protobuf",
          "module": "protobuf-javalite",
          "version": {
            "requires": "4.33.2"
          }
        },
        {
          "group": "com.lawnchair",
          "module": "iconloaderlib",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "com.lawnchair",
          "module": "searchuilib",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "com.lawnchair",
          "module": "animationlib",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.dynamicanimation",
          "module": "dynamicanimation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.profileinstaller",
          "module": "profileinstaller",
          "version": {
            "requires": "1.4.1"
          }
        },
        {
          "group": "androidx.recyclerview",
          "module": "recyclerview",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "androidx.preference",
          "module": "preference-ktx",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "com.github.ChickenHook",
          "module": "RestrictionBypass",
          "version": {
            "requires": "2.2"
          }
        },
        {
          "group": "dev.rikka.tools.refine",
          "module": "runtime",
          "version": {
            "requires": "4.4.0"
          }
        },
        {
          "group": "androidx.compose",
          "module": "compose-bom",
          "version": {
            "requires": "2025.12.01"
          },
          "attributes": {
            "org.gradle.category": "platform"
          }
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-util"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-tooling-preview"
        },
        {
          "group": "androidx.compose.ui",
          "module": "ui-text-google-fonts"
        },
        {
          "group": "androidx.compose.foundation",
          "module": "foundation"
        },
        {
          "group": "androidx.compose.material",
          "module": "material-icons-extended",
          "version": {
            "requires": "1.7.8"
          }
        },
        {
          "group": "androidx.compose.runtime",
          "module": "runtime-livedata"
        },
        {
          "group": "androidx.compose.material3",
          "module": "material3"
        },
        {
          "group": "androidx.compose.material3",
          "module": "material3-window-size-class"
        },
        {
          "group": "androidx.activity",
          "module": "activity-compose",
          "version": {
            "requires": "1.12.2"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-viewmodel-compose",
          "version": {
            "requires": "2.10.0"
          }
        },
        {
          "group": "androidx.navigation",
          "module": "navigation-compose",
          "version": {
            "requires": "2.9.6"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout",
          "version": {
            "requires": "2.2.1"
          }
        },
        {
          "group": "androidx.palette",
          "module": "palette-ktx",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.slice",
          "module": "slice-core",
          "version": {
            "requires": "1.1.0-alpha02"
          }
        },
        {
          "group": "com.google.accompanist",
          "module": "accompanist-adaptive",
          "version": {
            "requires": "0.37.3"
          }
        },
        {
          "group": "com.google.accompanist",
          "module": "accompanist-drawablepainter",
          "version": {
            "requires": "0.37.3"
          }
        },
        {
          "group": "com.google.accompanist",
          "module": "accompanist-permissions",
          "version": {
            "requires": "0.37.3"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.13.0"
          }
        },
        {
          "group": "io.github.fornewid",
          "module": "material-motion-compose-core",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "dev.kdrag0n",
          "module": "colorkt",
          "version": {
            "requires": "1.0.5"
          }
        },
        {
          "group": "io.coil-kt",
          "module": "coil-compose",
          "version": {
            "requires": "2.7.0"
          }
        },
        {
          "group": "me.xdrop",
          "module": "fuzzywuzzy",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "com.patrykmichalik.opto",
          "module": "domain",
          "version": {
            "requires": "1.0.18"
          }
        },
        {
          "group": "com.patrykmichalik.opto",
          "module": "core",
          "version": {
            "requires": "1.0.18"
          }
        },
        {
          "group": "com.patrykmichalik.opto",
          "module": "compose",
          "version": {
            "requires": "1.0.18"
          }
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-preferences",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-kotlinx-serialization",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "okhttp",
          "version": {
            "requires": "5.3.2"
          }
        },
        {
          "group": "androidx.room",
          "module": "room-runtime",
          "version": {
            "requires": "2.8.4"
          }
        },
        {
          "group": "androidx.room",
          "module": "room-ktx",
          "version": {
            "requires": "2.8.4"
          }
        },
        {
          "group": "com.github.topjohnwu.libsu",
          "module": "service",
          "version": {
            "requires": "6.0.0"
          }
        },
        {
          "group": "com.github.samanzamani",
          "module": "PersianDate",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "com.airbnb.android",
          "module": "lottie",
          "version": {
            "requires": "6.7.1"
          }
        },
        {
          "group": "sh.calvin.reorderable",
          "module": "reorderable",
          "version": {
            "requires": "2.5.1"
          }
        },
        {
          "group": "com.kieronquinn.smartspacer",
          "module": "sdk-client",
          "version": {
            "requires": "1.1.2"
          },
          "excludes": [
            {
              "group": "com.github.skydoves",
              "module": "balloon"
            }
          ]
        },
        {
          "group": "io.github.hokofly",
          "module": "hoko-blur",
          "version": {
            "requires": "1.5.5"
          }
        },
        {
          "group": "androidx.window",
          "module": "window",
          "version": {
            "requires": "1.5.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "launcher-sdk-1.0.0.aar",
          "url": "launcher-sdk-1.0.0.aar",
          "size": 15617526,
          "sha512": "9ffc5b96eb02b7f77477d78e276a72c04e3b92e56849b1013d325a82ef381556518f8c55774b7a38ef03e07a5fbd535e9b179054a0957567cacc2c29ab626c20",
          "sha256": "3f93ecfb79ae82282465d2e80230b6fb18c17f8d4ec6d11b2992b48fc9027048",
          "sha1": "c434cad5044da45fce19d404cdecd14c8451db75",
          "md5": "2520ef227cd0766267bcedfd2712f898"
        }
      ]
    },
    {
      "name": "lawnWithQuickstepPlayReleaseSourcesElements-published",
      "attributes": {
        "app": "lawn",
        "channel": "play",
        "com.android.build.api.attributes.ProductFlavor:app": "lawn",
        "com.android.build.api.attributes.ProductFlavor:channel": "play",
        "com.android.build.api.attributes.ProductFlavor:recents": "withQuickstep",
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm",
        "recents": "withQuickstep"
      },
      "files": [
        {
          "name": "launcher-sdk-1.0.0-sources.jar",
          "url": "launcher-sdk-1.0.0-sources.jar",
          "size": 9927009,
          "sha512": "005974e974683802d308dc1529f1fa96886cbc1cdd29648643b8d752f665c812110506272550d4bf57f86578db9894e05cea55c9f7c277cd75a330eb76785126",
          "sha256": "349bcead2d670af79a522be05ebff82c8cfeb41d1f7288a92cb0fd660d97a6e8",
          "sha1": "bd6c04f8e735e2c9f170b94a610c36d7d2157403",
          "md5": "2e601619b2ccd061fb2160a5bd1fbc5f"
        }
      ]
    }
  ]
}
