{
  "formatVersion": "1.1",
  "component": {
    "group": "com.lawnchair",
    "module": "viewcapture",
    "version": "1.0.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.1"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "viewcapture-1.0.2.aar",
          "url": "viewcapture-1.0.2.aar",
          "size": 78608,
          "sha512": "45aa2279e796e8ec2395e26a3e742196025a69c55cef6e5845edf4ef26682889558e5d647310df1f7f30672fff4ad61f8859fc88b2618c503ac2c47673fda4d5",
          "sha256": "3545ac34a958508e76c2bd39f4610830cc3ce79399dabb9946c16a2be8cffe30",
          "sha1": "eac2b103cf403de5ec606bb3f3ffdba572dc58e3",
          "md5": "4324eb3350d6996f2c45c891e5626d42"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.17.0"
          }
        },
        {
          "group": "com.google.protobuf",
          "module": "protobuf-javalite",
          "version": {
            "requires": "4.33.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "viewcapture-1.0.2.aar",
          "url": "viewcapture-1.0.2.aar",
          "size": 78608,
          "sha512": "45aa2279e796e8ec2395e26a3e742196025a69c55cef6e5845edf4ef26682889558e5d647310df1f7f30672fff4ad61f8859fc88b2618c503ac2c47673fda4d5",
          "sha256": "3545ac34a958508e76c2bd39f4610830cc3ce79399dabb9946c16a2be8cffe30",
          "sha1": "eac2b103cf403de5ec606bb3f3ffdba572dc58e3",
          "md5": "4324eb3350d6996f2c45c891e5626d42"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "viewcapture-1.0.2-sources.jar",
          "url": "viewcapture-1.0.2-sources.jar",
          "size": 40174,
          "sha512": "fa6a4b1aba6db7fbbf5d53c075cf081012f4a00a0318d6420a5cdef719c6dee143ce2f74f4d548dce73f82c8485a14bd49f2e6e136cfc9bfeb169382d13fb0dd",
          "sha256": "6e123ee06c6fe85e7445ec3ee447d1791fc47cffe072b813e678fa5beada8e1b",
          "sha1": "83f7e8f7c02c27d4b8ffa193783e30008aff9ee7",
          "md5": "dbb2f5b207f211e4ab1f7fb105c39025"
        }
      ]
    }
  ]
}
