{
  "formatVersion": "1.1",
  "component": {
    "group": "com.lawnchair",
    "module": "wmshell",
    "version": "1.0.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.1"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "wmshell-1.0.4.aar",
          "url": "wmshell-1.0.4.aar",
          "size": 111275,
          "sha512": "a6e380ed45d21a68307cddcc4a7af0f800c4b0e2b3df3c6b4317844676e181f687c1264c925cd1c95a71e508119999cd1b8298727374ad4212246659db91c018",
          "sha256": "c50ad91a90934811530e195b9dd60f7ded83fc806ee1d9385848d91540e8ec16",
          "sha1": "a0056cbf694534dd39fbf577882ec39e3d0629c3",
          "md5": "bb4013b1a73bd05ae91a66fb64608c1a"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.17.0"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "hilt-android",
          "version": {
            "requires": "2.57.2"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-animation",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.dynamicanimation",
          "module": "dynamicanimation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "wmshell-1.0.4.aar",
          "url": "wmshell-1.0.4.aar",
          "size": 111275,
          "sha512": "a6e380ed45d21a68307cddcc4a7af0f800c4b0e2b3df3c6b4317844676e181f687c1264c925cd1c95a71e508119999cd1b8298727374ad4212246659db91c018",
          "sha256": "c50ad91a90934811530e195b9dd60f7ded83fc806ee1d9385848d91540e8ec16",
          "sha1": "a0056cbf694534dd39fbf577882ec39e3d0629c3",
          "md5": "bb4013b1a73bd05ae91a66fb64608c1a"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "wmshell-1.0.4-sources.jar",
          "url": "wmshell-1.0.4-sources.jar",
          "size": 53218,
          "sha512": "bc3273207d11597cc070753751c36e679272cfd81cd28313d548aa63426e85cdf3819a03e3abd7ba58cc0809f707398b8e0f68812067d8053d43bef444fdb220",
          "sha256": "3ef43926ecf3c24768998cd0ae40347dd2a2d93117312caf3f84db75a2fca1d8",
          "sha1": "243f04023dc5dd2494f5e81fcb46f18229251069",
          "md5": "bed0622c94911eb1f566daaab3b1abf6"
        }
      ]
    }
  ]
}
