{
  "formatVersion": "1.1",
  "component": {
    "group": "com.lawnchair",
    "module": "common",
    "version": "1.0.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.1"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "common-1.0.2.aar",
          "url": "common-1.0.2.aar",
          "size": 4884,
          "sha512": "f3337af52b3d794c558a1121fed6af149e91cc421746fcf9661faab0851674f37f7bb74e92fa24686df7a052cd2407e52035dcbedcf770731ca386281ccd74de",
          "sha256": "add12552b3e4405958bc98af225bba702cbe443873205d0edb72bbd144f93c5f",
          "sha1": "daf1463e8851de370b897c28d0c11d29c8d0923b",
          "md5": "a757fbb580d456eba392c0bcb72d1885"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.17.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "common-1.0.2.aar",
          "url": "common-1.0.2.aar",
          "size": 4884,
          "sha512": "f3337af52b3d794c558a1121fed6af149e91cc421746fcf9661faab0851674f37f7bb74e92fa24686df7a052cd2407e52035dcbedcf770731ca386281ccd74de",
          "sha256": "add12552b3e4405958bc98af225bba702cbe443873205d0edb72bbd144f93c5f",
          "sha1": "daf1463e8851de370b897c28d0c11d29c8d0923b",
          "md5": "a757fbb580d456eba392c0bcb72d1885"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "common-1.0.2-sources.jar",
          "url": "common-1.0.2-sources.jar",
          "size": 3051,
          "sha512": "b8ed96891d2e27075180b87d69b1d8fabac0f90f294d70a67c0d32276c1ac409b288812200f1706659a4089d5f9ca068f30ac20d2ee57ee0da8069748275f9b6",
          "sha256": "021ec4726e2e441db6aace454c99b3aa53e27bc1d9735e59dc5f4d4d2e024265",
          "sha1": "62f9342b05b75398a29834f8f70a305467e91b3c",
          "md5": "da4164f1475e3c62fe6e39a2e6c5506a"
        }
      ]
    }
  ]
}
