{
  "formatVersion": "1.1",
  "component": {
    "group": "com.lawnchair",
    "module": "compatLibVT",
    "version": "1.0.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.1"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.lawnchair",
          "module": "compatLibVS",
          "version": {
            "requires": "1.0.3"
          }
        }
      ],
      "files": [
        {
          "name": "compatLibVT-1.0.3.aar",
          "url": "compatLibVT-1.0.3.aar",
          "size": 4941,
          "sha512": "66af1e9ec2263506e5c5fa423dfd514ebade29e1b935aff0f978ce59d01b592aeb12344b2e409c384291d0d74408eb01b19b0f1a6fec08260837196751cc1ead",
          "sha256": "66b06bc57a9c69a2c735436a537e672410ac74e80f56f9e2b0e070ab16a53616",
          "sha1": "ea5a1fe178606bea58c97f4ebd34c7dff804bf28",
          "md5": "e878d22c237e2b45173dfdecde5b66aa"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.17.0"
          }
        },
        {
          "group": "com.lawnchair",
          "module": "compatLibVS",
          "version": {
            "requires": "1.0.3"
          }
        }
      ],
      "files": [
        {
          "name": "compatLibVT-1.0.3.aar",
          "url": "compatLibVT-1.0.3.aar",
          "size": 4941,
          "sha512": "66af1e9ec2263506e5c5fa423dfd514ebade29e1b935aff0f978ce59d01b592aeb12344b2e409c384291d0d74408eb01b19b0f1a6fec08260837196751cc1ead",
          "sha256": "66b06bc57a9c69a2c735436a537e672410ac74e80f56f9e2b0e070ab16a53616",
          "sha1": "ea5a1fe178606bea58c97f4ebd34c7dff804bf28",
          "md5": "e878d22c237e2b45173dfdecde5b66aa"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "compatLibVT-1.0.3-sources.jar",
          "url": "compatLibVT-1.0.3-sources.jar",
          "size": 2841,
          "sha512": "6eb4d27a57e85e0df84b1d817f8197e1c1ce35f8161d50d52bc5702d429b72155754990270e824741be21cb2aa54b1dbcf82ee2288acb002a2aa78aedbf47e38",
          "sha256": "1415f75aa912e541bb73fdad796eeafb20ea2ccc9d9acb2c053cebb3c6f16272",
          "sha1": "8af92155e48013409e8d3d337e072e20995f225d",
          "md5": "c5e4d60031d8da4c0a5608e187cdf066"
        }
      ]
    }
  ]
}
