{
  "formatVersion": "1.1",
  "component": {
    "group": "com.lawnchair",
    "module": "anim",
    "version": "1.0.13",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.1"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "anim-1.0.13.aar",
          "url": "anim-1.0.13.aar",
          "size": 370007,
          "sha512": "34c7fd4e37d798fa2927d704312c58bf344d691fe0de3b8b92fabd25c1a702746b7c3eb9620f4f71e592fa8f4ca56e61084e83601f8b3f7beff3972b3ce2509e",
          "sha256": "5f6687a5847c028a37fc92e9c0e20210e22c983b80ffb5efd6ca5419adefbe6f",
          "sha1": "e745191898cf295c75411c863dcc6ec0db7a1901",
          "md5": "9caa963bcb34e1c6dc66a45855a0810c"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.17.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-animation",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "anim-1.0.13.aar",
          "url": "anim-1.0.13.aar",
          "size": 370007,
          "sha512": "34c7fd4e37d798fa2927d704312c58bf344d691fe0de3b8b92fabd25c1a702746b7c3eb9620f4f71e592fa8f4ca56e61084e83601f8b3f7beff3972b3ce2509e",
          "sha256": "5f6687a5847c028a37fc92e9c0e20210e22c983b80ffb5efd6ca5419adefbe6f",
          "sha1": "e745191898cf295c75411c863dcc6ec0db7a1901",
          "md5": "9caa963bcb34e1c6dc66a45855a0810c"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "anim-1.0.13-sources.jar",
          "url": "anim-1.0.13-sources.jar",
          "size": 126034,
          "sha512": "c4b66eb09ca1c72992067d63c90ca498ef7002845a62f582e5d716b96e0664908cd5d973e30e9efd22f600b8bec17651a4bf8636305214464a316d0c78cd2fa2",
          "sha256": "c3557b47e0d891d6f9c640bd4212acfb91b5c006e9032c146fe57101387b3c1d",
          "sha1": "be2c79adc63380add92aa27330cf4e5761b66085",
          "md5": "94f592813f2912c29a18b4e557a67a96"
        }
      ]
    }
  ]
}
