{
  "formatVersion": "1.1",
  "component": {
    "group": "com.lawnchair",
    "module": "compatLibVS",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.1"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.lawnchair",
          "module": "compatLibVR",
          "version": {
            "requires": "1.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "compatLibVS-1.0.0.aar",
          "url": "compatLibVS-1.0.0.aar",
          "size": 5287,
          "sha512": "9ed033e9d0286db7a2417338713499af8d210fb407392379e165bc6bd24b7e8572c57a1710485aefe4d5c37e62bc54e016bdf98ad12fbd63183aaf5576f5d1e1",
          "sha256": "ee1b7ef04e6f409dfe380522c4f516df724bc965b475b846f8efa306b23dc176",
          "sha1": "3a284567fb55c1a565fcd05beaa4e6d0c3935d00",
          "md5": "6b1ad8bd4d5e259f231dc447f5160033"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.17.0"
          }
        },
        {
          "group": "com.lawnchair",
          "module": "compatLibVR",
          "version": {
            "requires": "1.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "compatLibVS-1.0.0.aar",
          "url": "compatLibVS-1.0.0.aar",
          "size": 5287,
          "sha512": "9ed033e9d0286db7a2417338713499af8d210fb407392379e165bc6bd24b7e8572c57a1710485aefe4d5c37e62bc54e016bdf98ad12fbd63183aaf5576f5d1e1",
          "sha256": "ee1b7ef04e6f409dfe380522c4f516df724bc965b475b846f8efa306b23dc176",
          "sha1": "3a284567fb55c1a565fcd05beaa4e6d0c3935d00",
          "md5": "6b1ad8bd4d5e259f231dc447f5160033"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "compatLibVS-1.0.0-sources.jar",
          "url": "compatLibVS-1.0.0-sources.jar",
          "size": 3141,
          "sha512": "5312bf7febc989087adf90983846880cef358072e637f2ee10cb9f0ff7a4b0ff343b6ceda7bbcc1d0e49d0dc9f9d265e16954cbb786a02e73644a2f9648c7957",
          "sha256": "394a8f99ae34614b2505dd6a2c4f4e771c71e65571236bb96537a481fbec1b58",
          "sha1": "ad9eba2fd02af3a591571b909c9935cd36d27799",
          "md5": "460638eb7b3d49c30fa5bdc30a9ca83f"
        }
      ]
    }
  ]
}
