{
  "formatVersion": "1.1",
  "component": {
    "group": "com.lawnchair",
    "module": "compatLibVQ",
    "version": "1.0.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.1"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.lawnchair",
          "module": "compatLib",
          "version": {
            "requires": "1.0.2"
          }
        }
      ],
      "files": [
        {
          "name": "compatLibVQ-1.0.2.aar",
          "url": "compatLibVQ-1.0.2.aar",
          "size": 7083,
          "sha512": "f5bd49bc52da29d04548f52c6f8d3344ba26f29f900cbd73534b9f7db95be63c78ff15f7286638720605859d0dac6f13bef2e3859ac8d21471d90a9a3e67430e",
          "sha256": "f73ab952dbb1f9c46a3f81016b24320527d65ff06594b9fba1e59804e4233c9d",
          "sha1": "4ee22495f04ed25982425d9f8a3b2e9b9af6f53b",
          "md5": "461020b800706475dd037333a9786d37"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.17.0"
          }
        },
        {
          "group": "com.lawnchair",
          "module": "compatLib",
          "version": {
            "requires": "1.0.2"
          }
        }
      ],
      "files": [
        {
          "name": "compatLibVQ-1.0.2.aar",
          "url": "compatLibVQ-1.0.2.aar",
          "size": 7083,
          "sha512": "f5bd49bc52da29d04548f52c6f8d3344ba26f29f900cbd73534b9f7db95be63c78ff15f7286638720605859d0dac6f13bef2e3859ac8d21471d90a9a3e67430e",
          "sha256": "f73ab952dbb1f9c46a3f81016b24320527d65ff06594b9fba1e59804e4233c9d",
          "sha1": "4ee22495f04ed25982425d9f8a3b2e9b9af6f53b",
          "md5": "461020b800706475dd037333a9786d37"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "compatLibVQ-1.0.2-sources.jar",
          "url": "compatLibVQ-1.0.2-sources.jar",
          "size": 3671,
          "sha512": "5532395e12aba2a4d99f82ed135135a55378d5fa9c0bbb75c8f02cdd9cdc231d5175c627ae8abb68694d6116579cd1338645c5b715812cbd2d21d3323b710659",
          "sha256": "422b179036512f9b8c24589aebc54691274afed28f9e968f058af321b1952c35",
          "sha1": "8226fbc480ec680447da60bb864dc48708a94cf9",
          "md5": "08895449a7a5ed37ab0e099381b40efc"
        }
      ]
    }
  ]
}
