{
  "formatVersion": "1.1",
  "component": {
    "group": "com.lawnchair",
    "module": "wmshell",
    "version": "1.0.14",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.1"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "wmshell-1.0.14.aar",
          "url": "wmshell-1.0.14.aar",
          "size": 111275,
          "sha512": "a6e380ed45d21a68307cddcc4a7af0f800c4b0e2b3df3c6b4317844676e181f687c1264c925cd1c95a71e508119999cd1b8298727374ad4212246659db91c018",
          "sha256": "c50ad91a90934811530e195b9dd60f7ded83fc806ee1d9385848d91540e8ec16",
          "sha1": "a0056cbf694534dd39fbf577882ec39e3d0629c3",
          "md5": "bb4013b1a73bd05ae91a66fb64608c1a"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.17.0"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "hilt-android",
          "version": {
            "requires": "2.57.2"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-animation",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.dynamicanimation",
          "module": "dynamicanimation",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "wmshell-1.0.14.aar",
          "url": "wmshell-1.0.14.aar",
          "size": 111275,
          "sha512": "a6e380ed45d21a68307cddcc4a7af0f800c4b0e2b3df3c6b4317844676e181f687c1264c925cd1c95a71e508119999cd1b8298727374ad4212246659db91c018",
          "sha256": "c50ad91a90934811530e195b9dd60f7ded83fc806ee1d9385848d91540e8ec16",
          "sha1": "a0056cbf694534dd39fbf577882ec39e3d0629c3",
          "md5": "bb4013b1a73bd05ae91a66fb64608c1a"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "wmshell-1.0.14-sources.jar",
          "url": "wmshell-1.0.14-sources.jar",
          "size": 53232,
          "sha512": "fd641c7f620e411e6840ed02d3ad9cf11ee0e301c30e426ba3b8854db561015d0205ce1feea8d45e0a58f79a8b5013e16ef35eac9d4ef5fbe9c30712f34c3fc0",
          "sha256": "af5f56650d914c9f661eb7ab7423c294c142ea7db73e6a919009218f9c820fbb",
          "sha1": "5b42b3792497ca5221af0c5b5d7947d6f7929302",
          "md5": "e9bfe8b6edbc124403e59efefc93f54e"
        }
      ]
    }
  ]
}
