{
  "formatVersion": "1.1",
  "component": {
    "group": "com.lawnchair",
    "module": "compatLib",
    "version": "1.0.14",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.1"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "compatLib-1.0.14.aar",
          "url": "compatLib-1.0.14.aar",
          "size": 71471,
          "sha512": "84aa6cdea000dd0ee1d757c4a1b87edba6ae939864635adaa5d08df12da12ae2bd23acfcb7f442da22e52a5330580cf7d2d8582f0a1a112f0939ffe4301bd3d2",
          "sha256": "9558ef2c3da447128c6cd4478849a4b5cad18af446244753787bbb78e34ea2a3",
          "sha1": "90a393c2270152cd4ee08dd7cf080908ebf4f100",
          "md5": "51ef20309ea2058a3bfe0527886c3f3b"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.17.0"
          }
        }
      ],
      "files": [
        {
          "name": "compatLib-1.0.14.aar",
          "url": "compatLib-1.0.14.aar",
          "size": 71471,
          "sha512": "84aa6cdea000dd0ee1d757c4a1b87edba6ae939864635adaa5d08df12da12ae2bd23acfcb7f442da22e52a5330580cf7d2d8582f0a1a112f0939ffe4301bd3d2",
          "sha256": "9558ef2c3da447128c6cd4478849a4b5cad18af446244753787bbb78e34ea2a3",
          "sha1": "90a393c2270152cd4ee08dd7cf080908ebf4f100",
          "md5": "51ef20309ea2058a3bfe0527886c3f3b"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "compatLib-1.0.14-sources.jar",
          "url": "compatLib-1.0.14-sources.jar",
          "size": 45131,
          "sha512": "1c1703c549cb48899e4e0708ab70555117567a45b4632f702e78004f0fcf40e2d210b0453bb79b41a955e19148540a2a2bab4c30fbd7cfd017e67cec4ae47dbd",
          "sha256": "b86d065f44e6e702655d48b685a62b638f3666cd5410c9a8c0931ebb72b9f95b",
          "sha1": "d70a6559135f8fb6cfc13d690ed451beb0c7b7a4",
          "md5": "3288a5ec7127c41755a9ae56ec3480e5"
        }
      ]
    }
  ]
}
