{
  "formatVersion": "1.1",
  "component": {
    "group": "com.lawnchair",
    "module": "shared",
    "version": "1.0.14",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.1"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "shared-1.0.14.aar",
          "url": "shared-1.0.14.aar",
          "size": 367419,
          "sha512": "e832a006515e794558e9d0f9d80a5d15dec51c7aedb84a0267633852a36f7959b8b1e54a7cd297552316fb5d510fbca611531baa19e0b5e168fa4f71bcf0aba6",
          "sha256": "8537a8f92c6ad913820edef2a6220b99db8a075fb4c83ec3f28f114a047cf13b",
          "sha1": "d35e9dd4c5aee4be3ba0d2f9da4519380106ec62",
          "md5": "8a64a74d2bfd6331c32a10f77bcbb185"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.17.0"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "hilt-android",
          "version": {
            "requires": "2.57.2"
          }
        },
        {
          "group": "androidx.concurrent",
          "module": "concurrent-futures",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "shared-1.0.14.aar",
          "url": "shared-1.0.14.aar",
          "size": 367419,
          "sha512": "e832a006515e794558e9d0f9d80a5d15dec51c7aedb84a0267633852a36f7959b8b1e54a7cd297552316fb5d510fbca611531baa19e0b5e168fa4f71bcf0aba6",
          "sha256": "8537a8f92c6ad913820edef2a6220b99db8a075fb4c83ec3f28f114a047cf13b",
          "sha1": "d35e9dd4c5aee4be3ba0d2f9da4519380106ec62",
          "md5": "8a64a74d2bfd6331c32a10f77bcbb185"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "shared-1.0.14-sources.jar",
          "url": "shared-1.0.14-sources.jar",
          "size": 161164,
          "sha512": "815b3c04204ae3cab53fb8cbb77a031187e84daf0392ecef429d46e4813963b9a9b6ef8bfa62a9a7d684f5d059b676561156a9de34ce6d1885f8985540af4591",
          "sha256": "80095b6692ec13c8a108fa12bc76569c84f857ea5326166b6c214403dfae001d",
          "sha1": "fab429ae38bb92f51645dbd3954e4343b0fc54ce",
          "md5": "f27d522e92626ab873e6cca549fb735f"
        }
      ]
    }
  ]
}
