{
  "formatVersion": "1.1",
  "component": {
    "group": "com.lawnchair",
    "module": "shared",
    "version": "1.0.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.1"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "shared-1.0.3.aar",
          "url": "shared-1.0.3.aar",
          "size": 367419,
          "sha512": "e832a006515e794558e9d0f9d80a5d15dec51c7aedb84a0267633852a36f7959b8b1e54a7cd297552316fb5d510fbca611531baa19e0b5e168fa4f71bcf0aba6",
          "sha256": "8537a8f92c6ad913820edef2a6220b99db8a075fb4c83ec3f28f114a047cf13b",
          "sha1": "d35e9dd4c5aee4be3ba0d2f9da4519380106ec62",
          "md5": "8a64a74d2bfd6331c32a10f77bcbb185"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.17.0"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "hilt-android",
          "version": {
            "requires": "2.57.2"
          }
        },
        {
          "group": "androidx.concurrent",
          "module": "concurrent-futures",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "shared-1.0.3.aar",
          "url": "shared-1.0.3.aar",
          "size": 367419,
          "sha512": "e832a006515e794558e9d0f9d80a5d15dec51c7aedb84a0267633852a36f7959b8b1e54a7cd297552316fb5d510fbca611531baa19e0b5e168fa4f71bcf0aba6",
          "sha256": "8537a8f92c6ad913820edef2a6220b99db8a075fb4c83ec3f28f114a047cf13b",
          "sha1": "d35e9dd4c5aee4be3ba0d2f9da4519380106ec62",
          "md5": "8a64a74d2bfd6331c32a10f77bcbb185"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "shared-1.0.3-sources.jar",
          "url": "shared-1.0.3-sources.jar",
          "size": 161142,
          "sha512": "f033c0666bc146fa31d9943dc7e52981ca391e13ae8dec03999b848d7c41e7dd14cbc74f210e0cd94633329dfa01dd19d458ac2fea8a46284148f7149ca87085",
          "sha256": "28ad2faf6ed82798ad6d913f210c57ecb26549ef9ac3e2a81b1afe3ee052564c",
          "sha1": "8086b34559487af309f25791777ee5f9dfb1524b",
          "md5": "51d8e1d58d6b8506b33b89bdc7c73ac5"
        }
      ]
    }
  ]
}
