{
  "formatVersion": "1.1",
  "component": {
    "group": "com.lawnchair",
    "module": "unfold",
    "version": "1.0.14",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.1"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "unfold-1.0.14.aar",
          "url": "unfold-1.0.14.aar",
          "size": 162119,
          "sha512": "a93831e02b9f53b9dcad442a46b49148a591df4d0dd8872e4c780047f3a538a35ae0b1f5ba05f5d7166e3bbbf973611017d0370a113735a69587191e38e8d2a2",
          "sha256": "7d339ca290eb88b91e398036555732e403e96544a9f86311ab5386d3faa88d65",
          "sha1": "051780ad936e9372140ca2e6ff9fc0341a223864",
          "md5": "16ce82c190b09f544ea776243ec19c5e"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.17.0"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "hilt-android",
          "version": {
            "requires": "2.57.2"
          }
        },
        {
          "group": "androidx.concurrent",
          "module": "concurrent-futures",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-common",
          "version": {
            "requires": "2.10.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "unfold-1.0.14.aar",
          "url": "unfold-1.0.14.aar",
          "size": 162119,
          "sha512": "a93831e02b9f53b9dcad442a46b49148a591df4d0dd8872e4c780047f3a538a35ae0b1f5ba05f5d7166e3bbbf973611017d0370a113735a69587191e38e8d2a2",
          "sha256": "7d339ca290eb88b91e398036555732e403e96544a9f86311ab5386d3faa88d65",
          "sha1": "051780ad936e9372140ca2e6ff9fc0341a223864",
          "md5": "16ce82c190b09f544ea776243ec19c5e"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "unfold-1.0.14-sources.jar",
          "url": "unfold-1.0.14-sources.jar",
          "size": 84065,
          "sha512": "3dc08c2d91e701f5bdd7e65f02462ff1968544882a25132ab369fc2997e6a3328dc2ff07cec648056e77ba5628dbcda53bf9e2d1d3cc098a6ad1f7b18ce2b7aa",
          "sha256": "758e8e68a82161fb4ee7bf4f50bdc25d2d7a7a753367af5d4080931a2c7f1994",
          "sha1": "8e5492cafe839147e61ad636b6819fc8c77d0929",
          "md5": "cf2055c0d8dbff274a3b0761eb900358"
        }
      ]
    }
  ]
}
