{
  "formatVersion": "1.1",
  "component": {
    "group": "com.lawnchair",
    "module": "compatLib",
    "version": "1.0.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.1"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "compatLib-1.0.2.aar",
          "url": "compatLib-1.0.2.aar",
          "size": 71471,
          "sha512": "84aa6cdea000dd0ee1d757c4a1b87edba6ae939864635adaa5d08df12da12ae2bd23acfcb7f442da22e52a5330580cf7d2d8582f0a1a112f0939ffe4301bd3d2",
          "sha256": "9558ef2c3da447128c6cd4478849a4b5cad18af446244753787bbb78e34ea2a3",
          "sha1": "90a393c2270152cd4ee08dd7cf080908ebf4f100",
          "md5": "51ef20309ea2058a3bfe0527886c3f3b"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.17.0"
          }
        }
      ],
      "files": [
        {
          "name": "compatLib-1.0.2.aar",
          "url": "compatLib-1.0.2.aar",
          "size": 71471,
          "sha512": "84aa6cdea000dd0ee1d757c4a1b87edba6ae939864635adaa5d08df12da12ae2bd23acfcb7f442da22e52a5330580cf7d2d8582f0a1a112f0939ffe4301bd3d2",
          "sha256": "9558ef2c3da447128c6cd4478849a4b5cad18af446244753787bbb78e34ea2a3",
          "sha1": "90a393c2270152cd4ee08dd7cf080908ebf4f100",
          "md5": "51ef20309ea2058a3bfe0527886c3f3b"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "compatLib-1.0.2-sources.jar",
          "url": "compatLib-1.0.2-sources.jar",
          "size": 45111,
          "sha512": "18cf5983a96043e8929fafae89e18f8463ea898373b1771787533c70f6ee93c77d0fbb9becc8fd171ff331e9cf85270422e4480e43d8b8205f70f86e1060f172",
          "sha256": "766edfb85c497f0e25624c609ea79afec6441a3bc2e4beb90803f1e8083f3364",
          "sha1": "0b52e0beda1d061630766c9375484c9963622f00",
          "md5": "17efe40d72720f29b823371082b3842b"
        }
      ]
    }
  ]
}
