{
  "formatVersion": "1.1",
  "component": {
    "group": "com.lawnchair",
    "module": "compatLibVV",
    "version": "1.0.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.1"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.lawnchair",
          "module": "compatLibVU",
          "version": {
            "requires": "1.0.2"
          }
        }
      ],
      "files": [
        {
          "name": "compatLibVV-1.0.2.aar",
          "url": "compatLibVV-1.0.2.aar",
          "size": 4142,
          "sha512": "a19a94df00310c5b16aa12bb1d8c09751afb46d9040fef71bc1314a8b6d8f7eca66df4096630ef8353666fa6c5a78209b6e3d7fdebc8ed67b2e3a8cd054bbd3d",
          "sha256": "b1c4c1b0c2598cd84013313adc5bab4b96cf416874b226a6d2a34e282e394fb1",
          "sha1": "91b5a7cd033e00b45795484651f59cd7856fa056",
          "md5": "6cdcd4a2a0f2427ea46e9e7e3690a7cd"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.17.0"
          }
        },
        {
          "group": "com.lawnchair",
          "module": "compatLibVU",
          "version": {
            "requires": "1.0.2"
          }
        }
      ],
      "files": [
        {
          "name": "compatLibVV-1.0.2.aar",
          "url": "compatLibVV-1.0.2.aar",
          "size": 4142,
          "sha512": "a19a94df00310c5b16aa12bb1d8c09751afb46d9040fef71bc1314a8b6d8f7eca66df4096630ef8353666fa6c5a78209b6e3d7fdebc8ed67b2e3a8cd054bbd3d",
          "sha256": "b1c4c1b0c2598cd84013313adc5bab4b96cf416874b226a6d2a34e282e394fb1",
          "sha1": "91b5a7cd033e00b45795484651f59cd7856fa056",
          "md5": "6cdcd4a2a0f2427ea46e9e7e3690a7cd"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "compatLibVV-1.0.2-sources.jar",
          "url": "compatLibVV-1.0.2-sources.jar",
          "size": 2165,
          "sha512": "e21903fbbc3fcd469845a26fc0a298d57359b31b0c58abb068bfd26afe30cd0d3dac0efa0b50dadfe0e471d2435e8a1d2439af24598da75973b19f4892f83cb0",
          "sha256": "a5ec3d6ea875208b3a0966f6613b30eb0bc796c71337dcfdd018f74b56790126",
          "sha1": "971f9f0fe850429db9a95c1f840c8f592c09f63c",
          "md5": "1cf28a1b576dfdfffa32284daa2cfbf3"
        }
      ]
    }
  ]
}
