{
  "formatVersion": "1.1",
  "component": {
    "group": "com.lawnchair",
    "module": "iconloaderlib",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.1"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "iconloaderlib-1.0.0.aar",
          "url": "iconloaderlib-1.0.0.aar",
          "size": 148026,
          "sha512": "7059c6d00117e53b0155b4205ef8e0ebbee88f97fe1ca1e7499a8ef249189aa9a38ce52f3d88435e9161ff757e34d0a145c4ca8c29917c7842410fd304657200",
          "sha256": "c3c861ffb0a74eaa0eb4fc01bd88c616def03f340afa59318a4a7078e327a3cd",
          "sha1": "f87774fa3f655f8bf988ba3619e45b5c235c10e5",
          "md5": "b7428d3fc6121fcb9e702c3b9296a6c6"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.17.0"
          }
        },
        {
          "group": "androidx.palette",
          "module": "palette-ktx",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "iconloaderlib-1.0.0.aar",
          "url": "iconloaderlib-1.0.0.aar",
          "size": 148026,
          "sha512": "7059c6d00117e53b0155b4205ef8e0ebbee88f97fe1ca1e7499a8ef249189aa9a38ce52f3d88435e9161ff757e34d0a145c4ca8c29917c7842410fd304657200",
          "sha256": "c3c861ffb0a74eaa0eb4fc01bd88c616def03f340afa59318a4a7078e327a3cd",
          "sha1": "f87774fa3f655f8bf988ba3619e45b5c235c10e5",
          "md5": "b7428d3fc6121fcb9e702c3b9296a6c6"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "iconloaderlib-1.0.0-sources.jar",
          "url": "iconloaderlib-1.0.0-sources.jar",
          "size": 80973,
          "sha512": "46ad7b5891413e6ccd49f4e215e4f98ceac69d26c723699f05a4b1f285418a42f11d2d754684e1b33a28e489422d9671974415214a5f658f7045576ad6317b24",
          "sha256": "cd50cd941d914cfc0378d82dd3bb736ecb441b7b2b41ded50e1a3dbf3851fdc8",
          "sha1": "926cb5fb2d428ad49fdc9717c47611bd43541303",
          "md5": "6b693ec111408a274bfbb083ef612910"
        }
      ]
    }
  ]
}
